name: SQL Format Check

on: [pull_request]

env:
  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.9"
      - name: Install SQLFluff
        run: "pip install sqlfluff==1.0.0"
      - name: 'Fetch'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}
      - name: 'Lint models'
        run: |
          for file in $(git diff origin/${TARGET_BRANCH} HEAD --diff-filter=AM --name-only -- "*.sql") ; do
            sqlfluff lint ${file} --rules L001,L002,L004,L006,L010,L019 --dialect postgres
          done
